repos:
  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.2"
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-update
      - id: poetry-install
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.3
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: sh -c 'poetry install -qn && poetry run mypy .'
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies:
          - poetry
      - id: pytest
        name: pytest
        entry: sh -c 'poetry install -qn && poetry run pytest .'
        language: python
        types: [python]
        pass_filenames: false
        additional_dependencies:
          - poetry